In [1]:
from numpy  import *

ModuleNotFoundError: No module named 'numpy'

In [73]:
a = array( [2,3,4] )

In [74]:
print(a)

[2 3 4]

In [75]:
a.dtype

dtype('int64')

In [76]:
b = array([1.2, 3.5, 5.1])

In [77]:
b.dtype

dtype('float64')

In [78]:
array( [ (1.5,2,3), (4,5,6) ] )

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [82]:
array( [ ((1.5,2,3), (4,5,6)), ((1.5,2,3), (4,5,6)) ] )

array([[[ 1.5,  2. ,  3. ],
        [ 4. ,  5. ,  6. ]],

       [[ 1.5,  2. ,  3. ],
        [ 4. ,  5. ,  6. ]]])

In [79]:
arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [80]:
arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [83]:
arange( 0, 2, 0.3 )

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8])

In [84]:
arange(15).reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [85]:
arange(16).reshape(2, 4, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [86]:
a = arange(15).reshape(3, 5)

In [87]:
type(a)

numpy.ndarray

In [88]:
a.shape

(3, 5)

In [89]:
a.ndim

2

In [90]:
a.dtype.name

'int64'

In [91]:
a.itemsize

8

In [92]:
a.size

15

In [93]:
zeros( (3,4) )

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [94]:
ones( (2,3,4), dtype=int16 )

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [95]:
empty( (2,3) )

array([[  0.00000000e+000,   1.33856889e-316,   4.46513606e-317],
       [  2.80812644e-316,   4.46513606e-317,   2.84825604e-316]])

In [96]:
linspace( 0, 2, 9 )

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [97]:
def f(x,y):
    return 10*x+y
b = fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

Opérations basiques
-------------------

In [98]:
a = array( [20,30,40,50] )
b = arange( 4 )
a-b

array([20, 29, 38, 47])

In [99]:
a*b

array([  0,  30,  80, 150])

In [100]:
dot(a, b) # produit scalaire

260

In [115]:
dot(arange(4).reshape(2, 2), arange(4).reshape(2, 2))

array([[ 2,  3],
       [ 6, 11]])

In [125]:
dot(arange(4).reshape(4, 1), arange(4).reshape(1, 4))

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [124]:
dot(arange(4), arange(4))

14

In [120]:
dot(arange(6).reshape(2, 3), arange(6).reshape(3, 2))

array([[10, 13],
       [28, 40]])

In [101]:
a*3

array([ 60,  90, 120, 150])

In [102]:
b+6

array([6, 7, 8, 9])

In [103]:
b.sum()

6

In [104]:
arange(15).reshape(3, 5).sum()

105

In [105]:
b.min()

0

In [106]:
b.max()

3

In [107]:
b = arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [108]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [110]:
b.sum(axis=1)

array([ 6, 22, 38])

In [111]:
b.min(axis=1)

array([0, 4, 8])

In [112]:
help(b.min)

Help on built-in function min:

min(...)
    a.min(axis=None, out=None)
    
    Return the minimum along a given axis.
    
    Refer to `numpy.amin` for full documentation.
    
    See Also
    --------
    numpy.amin : equivalent function


In [113]:
exp(a)

array([  4.85165195e+08,   1.06864746e+13,   2.35385267e+17,
         5.18470553e+21])

In [116]:
sqrt(b)

array([[ 0.        ,  1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974,  2.64575131],
       [ 2.82842712,  3.        ,  3.16227766,  3.31662479]])

Opérateur crochet
-----------------

In [117]:
b = arange(8).reshape(2, 4)

In [118]:
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [126]:
>>> b[1,3]

7

In [127]:
b[-1,-1]

7

In [128]:
b[0:5, 1]

array([1, 5])

In [129]:
b[ : ,1]

array([1, 5])

In [130]:
b[1:3, : ]

array([[4, 5, 6, 7]])

In [131]:
for r in b:
    print(r)

[0 1 2 3]
[4 5 6 7]

In [132]:
for e in b.flat:
    print(e)

0
1
2
3
4
5
6
7

In [133]:
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [134]:
b.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [135]:
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [136]:
b.shape = (4, 2)

In [137]:
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [138]:
b.transpose()

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [139]:
a = floor(10*random.random((2,2)))
a

array([[ 9.,  2.],
       [ 5.,  5.]])

In [140]:
b = floor(10*random.random((2,2)))
b

array([[ 9.,  8.],
       [ 0.,  1.]])

In [146]:
vstack((a,b))

array([[ 9.,  2.],
       [ 5.,  5.],
       [ 9.,  8.],
       [ 0.,  1.]])

In [147]:
hstack((a,b))

array([[ 9.,  2.,  9.,  8.],
       [ 5.,  5.,  0.,  1.]])

Matrices
--------

In [148]:
A = matrix('1.0 2.0; 3.0 4.0')
A

matrix([[ 1.,  2.],
        [ 3.,  4.]])

In [149]:
A.T # transposée

matrix([[ 1.,  3.],
        [ 2.,  4.]])

In [150]:
X = matrix('5.0 7.0')
X

matrix([[ 5.,  7.]])

In [151]:
Y = X.T
Y

matrix([[ 5.],
        [ 7.]])

In [152]:
A*Y

matrix([[ 19.],
        [ 43.]])

In [153]:
A.I

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [154]:
solve(A, Y)

matrix([[-3.],
        [ 4.]])