S'installe en faisant :

    pip install numpy
    conda install numpy

In [1]:
from numpy  import *

In [2]:
import numpy as np
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',

In [3]:
a = array( [2,3,4] )

In [4]:
print(a)

[2 3 4]


In [5]:
a.dtype

dtype('int64')

In [30]:
int('1' * 15, base=2)

32767

In [11]:
b = array([1.2, 3.5, 5.1])

In [12]:
b.dtype

dtype('float64')

In [13]:
array( [ (1.5,2,3), (4,5,6) ] )

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [14]:
array( [ ((1.5,2,3), (4,5,6)), ((1.5,2,3), (4,5,6)) ] )

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[1.5, 2. , 3. ],
        [4. , 5. , 6. ]]])

In [15]:
arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [17]:
arange( 0, 2, 0.3 )

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [18]:
arange(15).reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [19]:
arange(16).reshape(2, 4, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [20]:
a = arange(15).reshape(3, 5)

In [21]:
type(a)

numpy.ndarray

In [22]:
a.shape

(3, 5)

In [23]:
a.ndim

2

In [24]:
a.dtype.name

'int64'

In [25]:
a.itemsize

8

In [26]:
a.size

15

In [28]:
zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
ones( (2,3,4), dtype=int16 )

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [4]:
empty( (2,3) , dtype=str)

array([['', '', ''],
       ['', '', '']], dtype='<U1')

In [37]:
linspace( 0, 2, 9 )

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [46]:
def f(x,y):
    return 10 * x + y

b = fromfunction(f, (5,4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [47]:
def f(x,y):
    return x + 2 *y + 2

b = fromfunction(f, (3,4), dtype=int)
b

array([[ 2,  4,  6,  8],
       [ 3,  5,  7,  9],
       [ 4,  6,  8, 10]])

Opérations basiques
-------------------

In [50]:
a = array( [20,30,40,50] )
b = arange( 4 )
a - b

array([20, 29, 38, 47])

In [51]:
a * b

array([  0,  30,  80, 150])

In [52]:
dot(a, b) # produit scalaire

260

In [54]:
arange(4).reshape(2, 2)

array([[0, 1],
       [2, 3]])

In [53]:
dot(arange(4).reshape(2, 2), arange(4).reshape(2, 2))

array([[ 2,  3],
       [ 6, 11]])

In [60]:
arange(4).reshape(2, 2) @ arange(4).reshape(2, 2)

array([[ 2,  3],
       [ 6, 11]])

In [55]:
arange(4).reshape(4, 1)

array([[0],
       [1],
       [2],
       [3]])

In [65]:
arange(4).reshape(1, 4)

array([[0, 1, 2, 3]])

In [59]:
dot(arange(4).reshape(4, 1), arange(4).reshape(1, 4))

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [62]:
arange(4).reshape(4, 1) @ arange(4).reshape(1, 4)

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [67]:
arange(4).reshape(4) @ arange(4)

14

In [63]:
dot(arange(4), arange(4))

14

In [68]:
dot(arange(6).reshape(2, 3), arange(6).reshape(3, 2))

array([[10, 13],
       [28, 40]])

---

In [73]:
print(a)
print(b)

[20 30 40 50]
[0 1 2 3]


In [70]:
a*3

array([ 60,  90, 120, 150])

In [71]:
b+6

array([6, 7, 8, 9])

In [74]:
b.sum()

6

In [75]:
arange(15).reshape(3, 5).sum()

105

In [76]:
b.min()

0

In [77]:
b.max()

3

In [78]:
b = arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [79]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [80]:
b.sum(axis=1)

array([ 6, 22, 38])

In [81]:
b.min(axis=1)

array([0, 4, 8])

In [82]:
help(b.min)

Help on built-in function min:

min(...) method of numpy.ndarray instance
    a.min(axis=None, out=None, keepdims=False, initial=<no value>, where=True)
    
    Return the minimum along a given axis.
    
    Refer to `numpy.amin` for full documentation.
    
    See Also
    --------
    numpy.amin : equivalent function



In [83]:
exp(a)

array([4.85165195e+08, 1.06864746e+13, 2.35385267e+17, 5.18470553e+21])

In [84]:
sqrt(b)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479]])

Opérateur crochet
-----------------

In [94]:
b = arange(20).reshape(4, 5)

In [95]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [96]:
>>> b[1,3]

8

In [99]:
b[-3,-2]

8

In [101]:
b[0:3, 1]

array([ 1,  6, 11])

In [102]:
b[ : ,1]

array([ 1,  6, 11, 16])

In [103]:
b[1:3, : ]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [104]:
b[1:3, ::2 ]

array([[ 5,  7,  9],
       [10, 12, 14]])

In [105]:
for r in b:
    print(r)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [106]:
for e in b.flat:
    print(e)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [107]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [108]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [109]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [110]:
b.shape = (10, 2)

In [111]:
b

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [112]:
b.transpose()

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]])

In [118]:
random.random((2,2))

array([[0.96541062, 0.36064125],
       [0.05441143, 0.79284896]])

In [120]:
from numpy.random import random

In [121]:
random((2,2))

array([[0.80482283, 0.38970794],
       [0.25734081, 0.58450787]])

In [122]:
from numpy import random

In [123]:
a = floor(10 * random.random((2,2)))
a

array([[3., 2.],
       [5., 0.]])

In [127]:
b = floor(10*random.random((2,2)))
b

array([[5., 2.],
       [0., 6.]])

In [128]:
vstack((a,b))

array([[3., 2.],
       [5., 0.],
       [5., 2.],
       [0., 6.]])

In [129]:
hstack((a,b))

array([[3., 2., 5., 2.],
       [5., 0., 0., 6.]])

Matrices
--------

In [130]:
A = matrix('1.0 2.0; 3.0 4.0')
A

matrix([[1., 2.],
        [3., 4.]])

In [131]:
A.T # transposée

matrix([[1., 3.],
        [2., 4.]])

In [132]:
X = matrix('5.0 7.0')
X

matrix([[5., 7.]])

In [133]:
Y = X.T
Y

matrix([[5.],
        [7.]])

In [134]:
A * Y

matrix([[19.],
        [43.]])

In [135]:
A.I

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [137]:
linalg.solve(A, Y)

matrix([[-3.],
        [ 4.]])